dist: bionic

language: go

go:
  - 1.11.x
  - 1.13.x
  - master

arch:
  - amd64
  - arm64
  - ppc64le

jobs:
  allow_failures:
    - go: master
  fast_finish: true
  exclude:
    - arch: arm64
      go: 1.11.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  global:
    - GO111MODULE=on

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - go test -v -race ./...
